name: Deploy to Pages
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Disabling Jekyll" > .nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
